In [1]:
import sys
sys.path.append('C:/Users/ryansenne/PycharmProjects/dCA1_Paper')

import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy import stats
%matplotlib inline

In [5]:
#Load pickles for FC and CxtA
with open(r'\Users\ryansenne\Desktop\Dill\collection_cxta_allmice.pkl', 'rb') as file:
    collection_cxta = pickle.load(file)

with open(r'\Users\ryansenne\Desktop\Dill\collection_cxtb_allmice.pkl', 'rb') as file:
    collection_cxtb = pickle.load(file)

with open(r'\Users\ryansenne\Desktop\Dill\collection_fc_allmice.pkl', 'rb') as file:
    collection_fc = pickle.load(file)

In [21]:
collection_fc.animals['astroF8'].accepted_traces

,C000,C001,C002,C003,C004,C005,C006,C007,C008,C009,...,C314,C315,C316,C318,C320,C321,C322,C323,C324,C325
0.000000,0.001433,0.000201,0.000294,0.019031,-0.000421,0.005958,0.008108,0.008207,0.001112,0.000938,...,0.019099,0.003781,-0.001862,0.009331,0.004755,0.005433,1.255701e-02,0.009587,0.007048,0.005876
0.099922,0.002470,0.001236,-0.000456,0.017175,0.000232,0.004651,0.006928,0.007324,0.001228,0.001020,...,0.018131,0.004537,-0.001186,0.008208,0.003555,0.004806,1.259048e-02,0.007673,0.004411,0.004589
0.199844,0.001775,0.002186,-0.001198,0.016479,0.000578,0.003421,0.006907,0.007696,0.000735,0.000561,...,0.015623,0.004585,-0.000204,0.006802,0.003791,0.003924,1.168121e-02,0.006855,0.004620,0.004550
0.299766,0.000487,0.001480,-0.000443,0.016435,0.003258,0.003589,0.007667,0.007599,-0.000512,0.000586,...,0.016761,0.004062,0.000545,0.007171,0.003568,0.003384,1.089228e-02,0.005315,0.004331,0.004120
0.399688,0.000071,0.001653,-0.000254,0.016391,0.006353,0.004425,0.006967,0.006601,-0.000302,0.001597,...,0.016213,0.004576,0.001169,0.007838,0.003059,0.003125,1.024276e-02,0.004959,0.004408,0.002898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359.419036,0.001598,0.001050,0.000503,0.003714,0.002474,0.001668,-0.000046,0.000315,0.000615,0.000593,...,-0.000020,0.002414,0.000416,0.000674,0.001223,0.000308,-2.215434e-04,0.002427,0.001338,0.000842
359.518957,0.000360,0.000619,0.000860,0.004852,0.002093,0.000648,-0.000929,0.001030,-0.000232,0.001422,...,-0.000082,0.002525,0.000599,0.000978,0.000806,0.000353,-1.822854e-05,0.001952,0.000538,0.000853
359.618879,0.000573,0.000261,0.001283,0.004116,0.001847,0.000642,-0.001658,0.001045,0.000302,0.001903,...,0.000180,0.002232,0.001130,0.001756,0.000501,0.000399,-2.011930e-04,0.002278,0.000491,0.001104
359.718801,0.001523,0.000159,0.000543,0.003752,0.001949,0.001034,-0.001594,-0.000627,0.000392,0.002102,...,0.000795,0.002175,0.001765,0.001941,0.001042,0.000175,3.005244e-07,0.001185,0.000593,0.000954
359.818723,0.001342,0.000297,0.000678,0.003328,0.000342,0.001714,-0.001635,-0.000223,-0.000025,0.002112,...,0.000039,0.001434,0.002551,0.001520,0.001141,-0.000077,2.378276e-05,0.001119,-0.000068,0.001372

In [22]:
collection_cxta.animals['astroF8'].accepted_traces

,C000,C001,C002,C003,C004,C005,C006,C007,C008,C009,...,C281,C282,C283,C284,C285,C286,C287,C288,C289,C290
0.000000,-0.005059,0.005928,0.014236,0.015417,0.002979,0.024930,0.006947,0.003664,0.010097,0.005791,...,0.002021,0.023956,0.018523,-0.003126,-0.009321,-0.004024,0.007847,0.019889,0.010539,0.004788
0.099922,-0.004222,0.005984,0.010169,0.013836,0.001269,0.017562,0.003299,0.002994,0.009119,0.003723,...,0.002348,0.016266,0.015457,-0.002037,-0.004913,-0.001817,0.005799,0.013381,0.006166,0.003006
0.199844,-0.001834,0.004882,0.008929,0.010711,0.000696,0.017003,0.002524,0.002145,0.008276,0.002991,...,0.000335,0.012360,0.013849,-0.002693,-0.004315,0.000595,0.005187,0.011296,0.005122,0.002814
0.299766,-0.001426,0.005022,0.008234,0.008454,0.000691,0.013527,0.002109,0.004064,0.008034,0.002559,...,0.000292,0.011678,0.011400,-0.003874,-0.003935,-0.000138,0.005321,0.010796,0.003441,0.003242
0.399688,-0.002417,0.005873,0.008308,0.009729,0.002032,0.014588,0.004307,0.004755,0.009617,0.002149,...,-0.000541,0.009734,0.010824,-0.003061,-0.000149,-0.001127,0.004616,0.009407,0.003538,0.003493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359.518909,-0.000857,0.015815,0.006058,0.002435,0.001696,0.000338,0.000756,0.001386,0.001344,0.000277,...,0.001360,0.003320,0.008317,0.002527,0.005345,0.000618,0.001475,0.001086,0.000675,0.001322
359.618830,-0.000290,0.016303,0.007279,0.002940,0.001802,-0.000384,0.001485,0.001154,0.002096,0.001334,...,0.000922,0.004313,0.007535,0.002003,0.005663,0.000580,0.001423,0.000904,0.001395,0.001753
359.718752,-0.001941,0.016299,0.008251,0.002703,0.001905,0.000404,0.001943,0.001558,0.001887,0.002208,...,0.001036,0.004353,0.006351,0.002066,0.006204,0.001783,0.001242,0.000519,0.000426,0.001523
359.818674,-0.001231,0.016876,0.010147,0.001273,0.000949,0.000354,0.002904,0.003494,0.001522,0.001244,...,0.001064,0.003236,0.006305,0.002460,0.006055,0.000758,0.001225,0.001344,0.000512,0.001271
359.918596,-0.000645,0.015198,0.009997,-0.000540,0.001810,0.001239,0.002406,0.003435,0.001608,0.001392,...,0.001099,0.003114,0.006878,0.000891,0.005258,0.000980,0.001099,0.001089,0.000232,0.000984