In [1]:
import pandas as pd
from onep import cell_registration,onephoton
import numpy as np
from onep.onephoton import CellReg

In [3]:
df_a = pd.read_pickle('/Users/amonast/Desktop/dCA1_astro/Analysis/UMAP_df/umap_recall_cxta_fixed_200neighbors.pkl')
df_b = pd.read_pickle('/Users/amonast/Desktop/dCA1_astro/Analysis/UMAP_df/umap_recall_cxtb_fixed.pkl')

In [4]:
csvs_a  = ['/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro3_traces/astro3_recall_traces_preprocess.csv',
        '/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro4_traces/astro4_recall_traces_preprocess.csv',
        '/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro5_traces/astro5_recall_traces_preprocess.csv',
        '/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro6_traces/astro6_recall_traces_preprocess.csv']

csvs_b = ['/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro7_traces/astro7_gen1_traces_preprocess.csv',
            '/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro8_traces/astro8_gen1_traces_preprocess.csv',
            '/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro9_traces/astro9_gen1_traces_preprocess.csv',
            '/Users/amonast/Desktop/dCA1_astro/Cell_Traces/astro10_traces/astro10_gen1_traces_preprocess.csv']

list_a = [pd.read_csv(file).drop('Unnamed: 0',axis=1) for file in csvs_a]
traces_a = pd.concat(list_a,axis=1).T


list_b = [pd.read_csv(file).drop('Unnamed: 0',axis=1) for file in csvs_b]
traces_b = pd.concat(list_b,axis=1).T

In [5]:
from onep.onephoton import load_registration_table
from onep import onephoton

In [6]:
astro_3 = onephoton.InscopixProcessing(session='recall', animal='astro3', data_directory='/Users/amonast/Desktop/dCA1_astro')
astro_3.read_inscopix()
astro_4 = onephoton.InscopixProcessing(session='recall', animal='astro4', data_directory='/Users/amonast/Desktop/dCA1_astro')
astro_4.read_inscopix()
astro_5 = onephoton.InscopixProcessing(session='recall', animal='astro5', data_directory='/Users/amonast/Desktop/dCA1_astro')
astro_5.read_inscopix()
astro_6 = onephoton.InscopixProcessing(session='recall', animal='astro6', data_directory='/Users/amonast/Desktop/dCA1_astro')
astro_6.read_inscopix()

In [7]:
shapes_a = [list_a[i].shape[1] for i in range(len(list_a))]
shapes_a

[45, 68, 53, 39]

In [8]:
luts = [astro.accepted_df.loc[astro.accepted_df['cell_status']==True] for astro in [astro_3,astro_4,astro_5,astro_6]]
lut = pd.concat(luts,axis=0,ignore_index=True)
lut.iloc[0:10]

   index  cell_status cell_IDs
0      0         True      C00
1      1         True      C01
2      2         True      C02
3      3         True      C03
4      4         True      C04
5      5         True      C05
6      6         True      C06
7      8         True      C08
8      9         True      C09
9     11         True      C11

In [9]:
fc_reg_inds = [load_registration_table(animal,[0,1],filter_accepted=True) for animal in ['astro3','astro4','astro5','astro6']]
fc_inds = pd.concat(fc_reg_inds,axis=0,ignore_index=True)[0]

only sessions:
['fc', 'recall']
Loading in registration table for only:
['fc', 'recall']
only sessions:
['fc', 'recall']
Loading in registration table for only:
['fc', 'recall']
only sessions:
['fc', 'recall']
Loading in registration table for only:
['fc', 'recall']
only sessions:
['fc', 'recall']
Loading in registration table for only:
['fc', 'recall']

In [10]:
animals_list = [[astro.animal]*shapes_a[i] for i,astro in enumerate([astro_3,astro_4,astro_5,astro_6])]
animals = [item for sublist in animals_list for item in sublist]

In [11]:
df_a['cell_id'] = traces_a.index.values
df_a['reg_idx'] = lut['index'].values
df_a['fc_idx'] = fc_inds
df_a['animal'] = animals

In [12]:
df_a

,x,y,waveform,cluster_id,cluster_color,cell_id,reg_idx,fc_idx,animal
0,4.607130,11.045631,"[28.670826381295047, 21.815370229641253, 19.12...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C00,0,0,astro3
1,4.342406,10.714427,"[23.319077131485905, 15.723410772849265, 12.56...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C01,1,4,astro3
2,4.357460,11.243212,"[1.0426172544881536, 1.0034856018615872, 1.103...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C02,2,5,astro3
3,5.058711,10.367497,"[9.950471022086901, 6.911519215843918, 6.06017...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C03,3,6,astro3
4,4.342914,10.726490,"[9.810414643874074, 6.716163180822961, 5.72043...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C04,4,7,astro3
...,...,...,...,...,...,...,...,...,...
200,5.405761,10.659324,"[-0.32069638057399835, 0.5175639387513534, 0.2...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C38,38,-1,astro6
201,5.851694,10.770348,"[4.437560239479756, 2.173014773130664, 1.57171...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C39,39,-1,astro6
202,5.648872,9.992742,"[2.4617043867145445, 2.9532810399654577, 2.393...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C40,40,-1,astro6
203,5.740173,11.254760,"[6.326951215527277, 3.6391093465544837, 2.5442...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C41,41,-1,astro6
204,4.981763,10.865788,"[10.196796113348183, 7.172899656324476, 6.3725...",2,"[0.4796, 0.01583, 0.01055, 1.0]",C42,42,-1,astro6

In [88]:
df_cluster.shape

(44, 9)

In [16]:
clusters = np.unique(df_a['cluster_id'])
p_cluster_animal = []
for cluster in clusters:
    df_cluster = df_a.loc[df_a['cluster_id']==cluster]
    percent_animal = [np.round(df_cluster.loc[df_cluster['animal']==ani].shape[0]/df_cluster.shape[0]*100,decimals=2) for ani in ['astro3','astro4','astro5','astro6']]
    p_cluster_animal.append(percent_animal)

In [17]:
p_cluster_animal

[[1.64, 1.64, 83.61, 13.11],
 [1.52, 95.45, 0.0, 3.03],
 [55.13, 5.13, 2.56, 37.18]]

In [18]:
for c,cluster in enumerate(p_cluster_animal):
    print(f"{cluster[0]} % of cells in cluster {c} are from animal astro3")
    print(f"{cluster[1]} % of cells in cluster {c} are from animal astro4")
    print(f"{cluster[2]} % of cells in cluster {c} are from animal astro5")
    print(f"{cluster[3]} % of cells in cluster {c} are from animal astro6")
    print("")

1.64 % of cells in cluster 0 are from animal astro3
1.64 % of cells in cluster 0 are from animal astro4
83.61 % of cells in cluster 0 are from animal astro5
13.11 % of cells in cluster 0 are from animal astro6

1.52 % of cells in cluster 1 are from animal astro3
95.45 % of cells in cluster 1 are from animal astro4
0.0 % of cells in cluster 1 are from animal astro5
3.03 % of cells in cluster 1 are from animal astro6

55.13 % of cells in cluster 2 are from animal astro3
5.13 % of cells in cluster 2 are from animal astro4
2.56 % of cells in cluster 2 are from animal astro5
37.18 % of cells in cluster 2 are from animal astro6

In [23]:
p_cluster_reactivated = []
for cluster in clusters:
    df_cluster = df_a.loc[df_a['cluster_id']==cluster]
    percent_r= np.round(df_cluster.loc[df_cluster['fc_idx']!=-1].shape[0]/df_cluster.shape[0]*100,decimals=2)
    p_cluster_reactivated.append(percent_r)

In [24]:
p_cluster_reactivated

[44.26, 30.3, 43.59]

In [25]:
for c,cluster in enumerate(p_cluster_reactivated):
    print(f"{cluster} % of cells in cluster {c} are reactivated")
    print("")

44.26 % of cells in cluster 0 are reactivated

30.3 % of cells in cluster 1 are reactivated

43.59 % of cells in cluster 2 are reactivated